### PR TITLE
Final Cartridge III Compatibility Improvements

### PR DESCRIPTION
**Pull request by markusC64**
Main points are emulation of cold start for FC3 and support for FC3+ (CRT only).

### CODE REVIEW

**Comment by rgc2000** [comment]
Warning, after this merge, FPGA code does no longer fit in Ultimate II (not plus) when compiling version with audio support (double 1541 drive version is ok).

 * Compilation ends with 
ERROR:Pack:1654 - The timing-driven placement phase encountered an error.

 * in ultimate_mb_700a.syr :
```
Device utilization summary:
---------------------------

Selected Device : 3s700aft256-4 

 Number of Slices:                     6209  out of   5888   105% (*) 
 Number of Slice Flip Flops:           5235  out of  11776    44%  
 Number of 4 input LUTs:              11580  out of  11776    98%  
    Number used as logic:             10874
    Number used as Shift registers:     241
    Number used as RAMs:                465
 Number of IOs:                         120
 Number of bonded IOBs:                 119  out of    161    73%  
    IOB Flip Flops:                     111
 Number of BRAMs:                        18  out of     20    90%  
 Number of MULT18X18SIOs:                 6  out of     20    30%  
 Number of GCLKs:                         4  out of     24    16%  
 Number of DCMs:                          1  out of      8    12%  

WARNING:Xst:1336 -  (*) More than 100% of Device resources are used
```

**Comment by markusC64** [comment]
That's inteesting, because I do have a successfull build.

But wait, I've merged "mb-bughunt" for my successfull build - should that make a difference?
Otherwise I'm using Xilinx ISE 12.1.

**Comment by thomasf** [comment]
quick unrelated question: is the readme up to date for the u2+ build dependencies (Altera Quartus 15.1).. I'm working on a docker container to use for a builder now, well, I'm more waiting for my slow internet connection than working on it right now.

**Comment by markusC64** [comment]
That should work. Fom my testing, you could also use Intel Quartus 17.1.

**Comment by GideonZ** [comment]
I am having a successful build here, too.
I am using Xilinx ISE 14.4.  (but for the software build it's important to use 13.x, or an SDK version that is stable.  Still working out issues with this, as my latest builds do not seem stable.)

**Comment by markusC64** [comment]
@rgc2000: Can you give Details about you Toolchain? ISE Version, if Xilinx SDK installed, its version.

**Comment by rgc2000** [comment]
I am using Xilinx ISE 13.4 with free license (ISE_WebPACK)

**Comment by rgc2000** [comment]
Well, error may not be fit related as Device utilisation summary was already telling me that Slices usage was 105% before the merge. But I don't see any details in any log about the encountered error

**Comment by rgc2000** [comment]
Something has changed in ISE, I have made several tests with different versions on 32-bit and 64-bit linux systems :
* Compiling OK with Xilinx ISE 13.1 (32 and 64 bits)
* Error in MAP stage with Xilinx ISE 13.4 (32 or 64 bits)

Conclusion, I will use ISE 13.1

**Pull request merged**
