### PR TITLE
Control target to power on and off drives

### PR DESCRIPTION
**Pull request by xlar54**
closed prev pull req and moved code to control target

### CODE REVIEW

**Comment by xlar54** [comment]
https://github.com/xlar54/ultimateii-dos-lib/tree/master/target

u-shell.prg to test

driveon, driveoff, drivestat

**Comment by xlar54** [comment]
btw, sorry - i should have put this on its own branch.  Will remember to do that next time.

**Comment by xlar54** [comment]
conflicts resolved

**Comment by GideonZ** [comment]
Merged.  However, there should be a control target document as well. Or at least it should be documented in the documentation repository. I haven't checked if you have done so. Would it be too much to ask?

**Comment by xlar54** [comment]
Oh yes, youre right.  Ill get that updated.

**Pull request merged**
