### PR TITLE
Issue 29

### PR DESCRIPTION
**Pull request by xlar54**
Regarding issue #29

### CODE REVIEW

**Comment by xlar54** [comment]
conflicts resolved

**Comment by xlar54** [comment]
can this be merged?

**Comment by GideonZ** [comment]
I would love to merge the drive on/off code, but there is something about the SEQ file type, which doesn't really belong in this branch... Not sure if I agree with this change.

**Comment by xlar54** [comment]
Yeah it somehow ended up in the branch - not sure why.  Ill remove it today.  But for that particular change, it was really to make the VFS more sd2iec-like.  I suppose it doesnt matter too much though.  Ill get that corrected today

**Comment by xlar54** [comment]
You actually have the drive on/off code merged into master, so I will close this pull request.  If you decide you want the D64, D71, D81 back in as a separate PR, just let me know.  Very simple addition if desired.  Thanks!  

Scott

**Pull request closed without merging**
