### PR TITLE
I removed 3 compilation warnings and a typo.

### PR DESCRIPTION
**Pull request by Zibri**
Done some cleanup.

### CODE REVIEW

**Review by GideonZ — CHANGES_REQUESTED** [review]
Some changes are not changes.; e.g. the whole function 'print_binary' seems to have been removed and added.

**Comment by Zibri** [comment]
> Some changes are not changes.; e.g. the whole function 'print_binary' seems to have been removed and added.

I don't understand. I just corrected a few lines. I did not touch print_binary.

**Comment by Zibri** [comment]
Anyway, I compiled the master source tree from your repository and the one from mine and they produce the exact same files.
(My compilation for now is only for u2plus)

**Comment by GideonZ** [comment]
Can you please make a pull request for ONLY these commits:
ea9c3361b2923dd9357e247be151915caa39549f
9c470e33451b58cd879318753526550e3464ed02

I cannot merge just a single commit from your pull request. Otherwise I'll have to bypass the pull request mechanism and cherry pick your changes.

**Comment by Zibri** [comment]
> Can you please make a pull request for ONLY these commits: [ea9c336](https://github.com/GideonZ/1541ultimate/commit/ea9c3361b2923dd9357e247be151915caa39549f) [9c470e3](https://github.com/GideonZ/1541ultimate/commit/9c470e33451b58cd879318753526550e3464ed02)
> 
> I cannot merge just a single commit from your pull request. Otherwise I'll have to bypass the pull request mechanism and cherry pick your changes.

How can I do that? And what's wrong with the other corrections? I just removed the warnings...

**Comment by rgc2000** [comment]
> 
Come on ! You know what's wrong. Do you really think that Gideon would just merge your "warning removals" without reading all the changes ? This has already been widely discussed. Hiding the c_pdm_target_pal change in your commit is not very smart.

**Comment by GideonZ** [comment]
> > 
> 
> Come on ! You know what's wrong. Do you really think that Gideon would just merge your "warning removals" without reading all the changes ? This has already been widely discussed. Hiding the c_pdm_target_pal change in your commit is not very smart.

Reminds me that I need to merge your merge request. I wanted to have a deeper look into separating the IEC communication layer from the IEC device layer, but as you may have noticed, I allow myself to get busy with ........ other things.

**Comment by Zibri** [comment]
> > 
> 
> Come on ! You know what's wrong. Do you really think that Gideon would just merge your "warning removals" without reading all the changes ? This has already been widely discussed. Hiding the c_pdm_target_pal change in your commit is not very smart.

What?! I didn't **hide** anything!

**Pull request closed without merging**
