### PR TITLE
Feature/1581emulation

### PR DESCRIPTION
**Pull request by xlar54**
Experimental 1581 drive emulation.

Features:
LOAD/SAVE/VERIFY
OPEN, INPUT#, *GET#, PRINT#, CLOSE
Command channel
Copy
Rename
Scratch
Format
Initialize
Validate
U1 - Block read*
U2 - Block write
B-F - Block free
B-A - Block allocate
B-P - Buffer pointer
Partition (CBM) access
Subdirectories in partitions

Missing:
M-R (some code added where some programs check if 1581)
M-W
M-E
REL files

The missing items will be added soon, but I wanted to get this in front of you to look at, while i have some UII+ testers try things out. 

Known Issues:
* GET# seems to miss ever other character.  This appears to exist in the current code (see my previous issue - https://github.com/GideonZ/1541ultimate/issues/109).  Stepping through it in the debugger works fine.  Something strange is going on when running on its own.  **(FIXED)**

* Block read seems to have the same issue as GET# to a degree.  It will properly read the block, but at the 214th character, when sending to the system, it returns bad data.  Stepping through it in the debugger works fine.  **this seems to be fixed as of 10/21, although the reason for it is unclear.**

* The memory commands will be implemented to the point at which some fastloaders will properly execute.  GEOS for example.  sd2iec code has all of this in it.  For now, there is just enough to help programs identify the drive as a 1581

* Allocation on a real 81 disk is upwards and downwards from track 40. This is to speed up reading the disk, so the head doesnt have to travel very far.  At this point, Im just starting sequentially at track 1, looking for free sectors.  Will fix this soon, but it has no impact currently. **(FIXED)**

As it stands, the code can be used to read and write to a 1581 disk image, and basic DOS functions.  I like how the soft IEC can be made drive C, and have various modes, should more drive types be implemented later. 

**To use**:  Go to the UII+ menu, press F2, select "Software IEC Settings", then you can change "Soft Drive C Mode" to either "Native" (your implementation) or "1581".  The Bus ID remains the same for either mode.  After this, you can mount a D81 image.  You can always switch back to Native mode.

### CODE REVIEW

**Comment by markusC64** [comment]
Note: This does not compile for the 1541 Ultimate II (non plus) - even after adjusting the Makefile:

/opt/Xilinx/SDK/2018.2/gnu/microblaze/lin/bin/../lib/gcc/microblaze-xilinx-elf/7.2.0/../../../../microblaze-xilinx-elf/lib/libc.a(lib_a-signalr.o): In function `_kill_r':
(.text+0x2c): undefined reference to `kill'
/opt/Xilinx/SDK/2018.2/gnu/microblaze/lin/bin/../lib/gcc/microblaze-xilinx-elf/7.2.0/../../../../microblaze-xilinx-elf/lib/libc.a(lib_a-signalr.o): In function `_getpid_r':
(.text+0x94): undefined reference to `getpid'
make[1]: *** [output/ultimate.out] Fehler 1
make[1]: Leaving directory `/tmp/1541u2/target/software/mb_ultimate'

**Comment by markusC64** [comment]
And for the U64, the application becomes too large because you changed from optimization of size to no optimization (probably for debugging), so please apply

```
--- a/target/software/nios2_u64/Makefile
+++ b/target/software/nios2_u64/Makefile
@@ -187,7 +187,7 @@ SRCS_IEC = iec_code.iec
 SRCS_NANO = nano_minimal.nan

 PATH_INC =  $(addprefix -I, $(VPATH))
-OPTIONS  = -g -ffunction-sections -O0 -DOS -DDEVELOPER=0 -DNIOS=1 -DCLOCK_FREQ=66666667 -DU64=1 -Wno-write-strings -mno-hw-div -mno-hw-mul -mno-hw-mulx
+OPTIONS  = -g -ffunction-sections -Os -DOS -DDEVELOPER=0 -DNIOS=1 -DCLOCK_FREQ=66666667 -DU64=1 -Wno-write-strings -mno-hw-div -mno-hw-mul -mno-hw-mulx
 COPTIONS = $(OPTIONS) -std=gnu99
 CPPOPT   = $(OPTIONS) -fno-exceptions -fno-rtti -fno-threadsafe-statics -fpermissive
 LINK    = $(BSP)/linker.x

```

**Comment by GideonZ** [comment]
In my master branch, the option -Os is still there. Are you sure this is
not a change that you made yourself locally?

(In fact, locally on my machine, I have a *nios2_u64_dev* directory where
this line is different in the makefile. I use that to run my builds from
Eclipse. So I don't use the *nios2_u64* directory for development.)

**Comment by markusC64** [comment]
That is for xlar54's merge request. If you would merge it, -Os is not  there any more. Look at the changes the github gui displays and search fior "Makefile".

And that comment bas been for xlar54.

**Comment by xlar54** [comment]
Understood.  Will fix that now, thank you.

**Comment by xlar54** [comment]
> Note: This does not compile for the 1541 Ultimate II (non plus) - even after adjusting the Makefile:
> 
> /opt/Xilinx/SDK/2018.2/gnu/microblaze/lin/bin/../lib/gcc/microblaze-xilinx-elf/7.2.0/../../../../microblaze-xilinx-elf/lib/libc.a(lib_a-signalr.o): In function `_kill_r': (.text+0x2c): undefined reference to `kill'
> /opt/Xilinx/SDK/2018.2/gnu/microblaze/lin/bin/../lib/gcc/microblaze-xilinx-elf/7.2.0/../../../../microblaze-xilinx-elf/lib/libc.a(lib_a-signalr.o): In function `_getpid_r': (.text+0x94): undefined reference to `getpid'
> make[1]: *** [output/ultimate.out] Fehler 1
> make[1]: Leaving directory `/tmp/1541u2/target/software/mb_ultimate'

I really am not sure how to address this one as I dont have a UII to test with, nor am I sure why it's referencing "getpid".  I dont think I use that anywhere. Ill look into it, but if you have any suggestions, Id definitely appreciate it.

**Comment by markusC64** [comment]
I have no clue. Before merging your branch, it does compile, after merging it, it does not. FYI: I merged to git master with my merge request applied that make compiling possible.

Anyway, even without a 1541 U2, you can compile it (you see from my extract of error messages what makefile to adjust).

**Comment by xlar54** [comment]
ok, ill see what I can do.  Thanks again Markus.  Still learning.

**Comment by markusC64** [comment]
Just a warning: When building untested U2 installers, please do not give them away for testing. They probably won't even install due to a too large application.
IMO it's up to gideon to decide which features to remove to make that fitting again.

I'd suggest the user should decide whether to flash NTSC or PAL ROMs - not both any more. That would give us some free space without removing other features. The missing ROMs can be loaded from CRT if needed.

**Comment by xlar54** [comment]
Absolutely will heed this.  I have provided some UII+ installers to testers - I have a UII+ and it worked fine, but yes - I dont know enough about the U2 specifically to even attempt it.

**Comment by GideonZ** [comment]
Ah yes, I was mistaken.. :) Sorry!

**Comment by xlar54** [comment]
The issues listed at the start of this regarding GET# and the block read command seems to be fixed at this point.  Sector editors work that read and write buffers, so its possible there was an error in my test code.

**Comment by xlar54** [comment]
It is also worth mentioning that some programs rely on various M-R commands to determine if the drive is a 1581.  Ill look into attaching a ROM in order to keep this in line with the other drives

**Comment by markusC64** [comment]
@xlar54 : Please explain "had to rmv markus code 4 GEOS MP3 due to conflict"... This code just loads data to the REU.

**Comment by xlar54** [comment]
> @xlar54 : Please explain "had to rmv markus code 4 GEOS MP3 due to conflict"... This code just loads data to the REU.

Sure.  But first, note that my branch will not be going into the official release (we are looking at a better long term FPGA approach) so this really isnt a valid PR anymore.  

"software/filetypes/filetype_d64.cc"  you grab all 4 different file types (D64, 71, 81, and DNP) for the context menu instead of just D64.  This code causes my 81 emulation code to not provide the context menu it needs when mounting a D81 in filetype_d81.cc.  Thats all really.  Gideon and I talked about this being a good and interesting starting point on some future work, so no expectations of it going official.  We will all probably want to meet up and discuss his vision soon though.

**Comment by markusC64** [comment]
@xlar54 Well, I might have an idea how to solve that problem - if my idea works, I'll send you the necessary fix that allows both improvements to co-exist.

**Comment by xlar54** [comment]
no longer needed (thank goodness!)

**Pull request closed without merging**
