### PR TITLE
A more pythonic sock.py

### PR DESCRIPTION
**Pull request by thomasf**
I tested the "p" command which still worked after cleaning up the code. There should not be any functional differences from this patch even though I am not able to test all of them since I don't really know what they do or exactly how they work yet.

### CODE REVIEW

**Comment by thomasf** [comment]
I will make some more edits..

**Comment by thomasf** [comment]
After sleeping on it I believe that an ultimate CLI tool should probably be written in Go instead.

- Go binaries is statically linked, no python runtime required.
- Go binaries are very easy to cross compile so that binaries can be quickly distributed to anyone interested.
- Go is way less error prone than C.

I will start writing the go version of this tool in a separate repository, maybe this weekend.

and....

I also continued to develop the script a while more after the basic compatibility fixes.

I won't include these changes in this pull request because I don't understand
enough yet about u1541 firmware yet so I can't really finish it anyway.


```py
import argparse
import socket
import sys
from struct import pack


class Socket:
    '''demonstration class only
      - coded for clarity, not efficiency
    '''

    def __init__(self, sock=None,):
        self.host = host
        if sock is None:
            self.sock = socket.socket(
                socket.AF_INET, socket.SOCK_STREAM)
        else:
            self.sock = sock

    def connect(self, host, port):
        self.sock.connect((host, port))

    def send(self, msg):
        totalsent = 0
        while totalsent < len(msg):
            sent = self.sock.send(msg[totalsent:])
            if sent == 0:
                raise RuntimeError("socket connection broken")
            totalsent = totalsent + sent

    def recv(self, maxlen):
        chunks = []
        bytes_recd = 0
        while bytes_recd < maxlen:
            chunk = self.conn.recv(min(maxlen - bytes_recd, 2048))
            bytes_recd = bytes_recd + len(chunk)
            print(bytes_recd)
            if chunk == '':
                print("Number of chunks received so far:",
                      len(chunks), bytes_recd)
                break
                # raise RuntimeError("socket connection broken")
            chunks.append(chunk)
        return ''.join(chunks)

    def serve(self, port):
        self.sock.bind(('', port))
        self.sock.listen(2)
        conn, addr = self.sock.accept()
        print(conn, addr)
        self.conn = conn


class CommandClient:

    _SOCKET_CMD_DMA = 0xFF01
    _SOCKET_CMD_DMARUN = 0xFF02
    _SOCKET_CMD_KEYB = 0xFF03
    _SOCKET_CMD_RESET = 0xFF04
    _SOCKET_CMD_WAIT = 0xFF05
    _SOCKET_CMD_DMAWRITE = 0xFF06
    _SOCKET_CMD_DMAJUMP = 0xFF09
    _SOCKET_CMD_LOADSIDCRT = 0xFF71

    def __init__(self, host, port=64):
        self.host = host
        self.port = port
        self.socket = None

    def connect(self):
        """Open a connection to the commodore computer command control."""
        if self.socket is None:
            self.socket = Socket()
        self.socket.connect(self.host, self.port)

    def close(self):
        """"Close the client connection."""
        self.socket.sock.shutdown(0)
        self.socket.sock.close()

    def reset(self):
        """Reset the Commodore computer."""
        self.socket.send(pack("<H", self._SOCKET_CMD_RESET))
        self.socket.send(pack("<H", 0))

    def dma_run(self, bytes):
        if len(bytes) > 65536:
            raise ValueError("cannot send more than 64k of data")
        if len(bytes) == 0:
            raise ValueError("no bytes to send")
        self.socket.send(pack("<H", self._SOCKET_CMD_DMARUN))
        self.socket.send(pack("<H", len(bytes)))
        self.socket.send(bytes)

    def wait(self, duration):
        raise NotImplemented()
        # # wait 3 seconds
        # s.send(pack("<H", self._SOCKET_CMD_WAIT))
        # s.send(pack("<H", 600))

    def dma_write(self, addr, data):
        raise NotImplemented()
        # # write border color
        # s.send(pack("<H", 0xFF06))
        # s.send(pack("<H", 3))
        # s.send(pack("<H", 0xD020))
        # s.send(pack("<B", 7))

    def load_sidcrt(self, bytes):
        if len(bytes) > 65536:
            raise ValueError("cannot send more than 64k of data")
        if len(bytes) == 0:
            raise ValueError("no bytes to send")
        self.socket.send(pack("<H", self._SOCKET_CMD_LOADSIDCRT))
        self.socket.send(pack("<H", len(bytes)))
        self.socket.send(bytes)

    def keys(self, text):
        # # TODO(tomasf): Understand what sending multiple keys at once means.
        # s = text.encode('ascii')
        # self.socket.send(pack("<H", self._SOCKET_CMD_KEYB))
        # self.socket.send(pack("<H", len(s)))
        # self.socket.send(pack("<{}B".format(len(s)), *s))
        # print(len(s))
        # print(pack("<{}B".format(len(s)), *s))
        s = text.encode('ascii')
        for k in s:
            self.socket.send(pack("<H", self._SOCKET_CMD_KEYB))
            self.socket.send(pack("<H", 1))
            self.socket.send(pack("<B", k))


if __name__ == "__main__":

    argv = sys.argv


    if len(argv) < 2:
        print("no command given")
        sys.exit(1)
    command = argv[1]
    host = "localhost"

    if (argv[1] == 'c'):
        # TODO(thomaf): figure out the purpouse of this command
        s = Socket()

        message = (("abcdefghijklmnopqrstuvwxyz" * 5) +
                   ("0123456789" * 10)) * 10
        # print message
        message = message * 2000

        if (len(argv) == 3):
            s.connect(argv[2], 5001)
        else:
            s.connect("localhost", 5001)
        s.send(message)
        s.sock.shutdown(0)
        s.sock.close()

    elif (command in ['t', 'trace']):
        s = Socket()

        if (len(argv) == 3):
            s.connect(argv[2], 5002)
        else:
            s.connect("localhost", 5002)
        s.conn = s.sock
        msg = s.recv(2*1024*1024)
        text_file = open("trace.log", "wb")
        text_file.write(msg)
        text_file.close()
        s.sock.shutdown(0)
        s.sock.close()

    elif (command in ['u']):
        # TODO(thomaf): figure out the purpouse of this command, firmware update?
        with open(argv[2], "rb") as f:
            bytes = f.read(2*1024*1024)  # max 2 Meg
            if bytes != "":
                s = Socket()
                s.connect(argv[3], 12345)
                s.send('\0\1\0\0')
                s.send(bytes)
                s.sock.shutdown(0)
                s.sock.close()

    elif (command == 'U'):
        # TODO(thomaf): figure out the purpouse of this command, firmware update?
        with open(argv[2], "rb") as f:
            bytes = f.read(2*1024*1024)  # max 2 Meg
            if bytes != "":
                s = Socket()
                s.connect(argv[3], 12345)
                s.send('\1\0\0\0')
                s.send(bytes)
                s.sock.shutdown(0)
                s.sock.close()

    elif (command in ['reset']):
        c = CommandClient(argv[2])
        c.connect()
        c.reset()
        c.close()

    elif (command in ['s', "sidcrt"]):
        with open(argv[2], "rb") as f:
            bytes = f.read(65536)  # max 64K
            c = CommandClient(argv[3])
            c.load_sidcrt(bytes)
            c.close()

    elif (command in ['k', "keys"]):
        c = CommandClient(argv[2])
        c.connect()

        c.keys(" ".join(argv[3:]))
        # c.keys(30)
        c.close()

    elif (command in ['p', 'dma_run']):
        with open(argv[2], "rb") as f:
            bytes = f.read(65536)  # max 64K
            c = CommandClient(argv[3])
            c.connect()
            c.dma_run(bytes)
            c.close()

    elif (command in ['dma_write']):
        c = CommandClient(argv[2])
        addr = bytearray.fromhex(argv[3])
        bytes = bytearray.fromhex(argv[4])
        c.connect()
        c.dma_write(addr, bytes)
        c.close()

    elif command == "serve":
        s = Socket()
        s.serve(5001)
        msg = s.recv(1024*1024)
        print("Received: ", len(msg), "bytes")
        s.sock.shutdown(0)
        s.sock.close()

    else:
        print("'{}'' is not a valid command".format(command))

```

**Comment by markusC64** [comment]
BTW: There is a perl CLI tool for that in my repository: https://github.com/markusC64/1541ultimate2/tree/tools

**Comment by thomasf** [comment]
Great, I think the easy cross platform/arch static binary thing with Go is a "killer feature" for maintaining and distributing a more user friendly tool.. 
Telling non developer windows users to install the right version of perl or python probably causes more headache that it's worth :) 

I'm not sure exactly who the target audience should be but a web interface could also be added so that people can drag'n'drop prg/d64 images directly to a page to load them to avoid the command prompt.

**Comment by markusC64** [comment]
For windows users, I offer a ready made EXE in the releases section :-)

Linux users usually have perl available, and for OS X, there is a perl preinstalled available from command line.

Could you make sue there is script compatibility between the solutions?

BTW: In one of my mails from Gideon he announced that there is a plan to replace TCP port 64 by a REST interface. In best case, that would mean to the user: Update 1541u2.pl/.exe or update your solution and eveything is working again.

**Comment by thomasf** [comment]
I like the script language,.. I will implement it as well.

**Comment by GideonZ** [comment]
Please note that this debug interface will disappear soon. It is meant for development and not for the masses. So updating / improving scripts like this, is a bit of a dead end.

**Comment by thomasf** [comment]
Ok.. will it be replaced with some equivalent features later? Being able to dma transfer and control to the computer is kind of important if one want to do c64 cross development.

**Comment by markusC64** [comment]
I aleady have given you the hint above: "BTW: In one of my mails from Gideon he announced that there is a plan to replace TCP port 64 by a REST interface. In best case, that would mean to the user: Update 1541u2.pl/.exe or update your solution and eveything is working again.".

**Comment by thomasf** [comment]
Great,, I just wanted to be sure since I was getting mixed signal about it..

**Comment by markusC64** [comment]
Anyway: Until the REST Interface is available, the 1541u2.pl tool is needed. Other developments should just call it so only one tool needs to be updated when REST is available.
So if you think a GUI would be fine, just make it call 1541u2.pl/.exe and eveything should be fine, as we only have one quite little tool to be updated.

**Comment by thomasf** [comment]
Yeah, I will hold off writing anything new until there at least is a stable interface. For the time being I just want the dmarun feature anyways so I will use whatever works.

**Comment by thomasf** [comment]
@markusC64  

Whats the point of having a `send` command in the DSL?  Is it because not all firmware versions have the large packet support? I guess that it's an experimental tool at this point but at some point the tool itself could be able to figure out how to send stuff?

Also, reading from stdin seems to be missing maybe `read prg from stdin` if regular file names requires to be quoted `stdin` could be read as a symbol and mapped correctly?

...

btw. I wrote myself a small bash script to be able to batch demos to watch from the PC since I have ~15 years of scene release backlog :) 

script below screenshots:

image

image

```bash
#!/bin/bash

set -e
# set -x

# usage: ut [filename.d64/prg] [filename2.d64/prg]...
# if started without an argument https://github.com/junegunn/fzf will be invoked
# and show a recrursive list of all prg/d64s under current directory,
# tab selects multiple entries, files loads in order of selection.


u2ip=${u2ip:-192.168.1.251}

u() {
  1541u2 ${u2ip} "${@}"
}

# resets the c64 and activate the fastloader
reset_fastload() {
  u -e "reset-c64" -e "send"
  sleep 1.2
  u -e "keys 136" -e "send" # f7
  sleep 0.3
}

# reset, activate fastloader and load *
reset_run() {
  reset_fastload
  u -e "keys 133" -e "send" # f1
  sleep 0.3
  u -e "keys 13" -e "send" # enter
}

# cycl
action() {
  local filename=${1}
  local act="nop"
  while [ "$act" != "0" ]; do
    read -p "enter=next r=reset+load+run x=reset v=vice l=reload? " act
    case ${act} in
      l)
        load ${filename}
        ;;
      v)
        x64sc ${filename} >/dev/null 2>/dev/null &
        ;;
      r)
        reset_run
        ;;
      x)
        reset_fastload
        ;;
      *)
        act="0"
        echo ""
        ;;
    esac
  done
}

# run directly if .prg, mount if d64
load() {
  local filename=${1}
  local ext="${filename##*.}"
  ext="${ext,,}"
  case ${ext} in
    d64)
      echo "MOUNT ${filename}"
      c1541 -attach "${filename}" -dir
      u -c d64:"${filename}"
      ;;
    prg)
      echo "RUN ${filename}"
      u -c run:"${filename}"
      ;;
    *)
      echo "Nothing to do for $filename"
      exit 1
      ;;
  esac
}

if [ "$#" -lt 1 ]; then
  filenames=$(find . -iname \*.d64 -or -iname \*.prg | fzf --reverse -m)
  IFS=$'\n'
  for filename in ${filenames}; do
    load ${filename}
    action ${filename}
  done
else
  for filename in "${@}"; do
    load "${filename}"
    action "${filename}"
  done
fi

```

**Comment by markusC64** [comment]
For having "send" at all: It is to give the user control what is contained in the packet being sent - as a packet can contain multiple commands.

For having two send commands: Large packets ae only supported since official firmware 3.2 - which happens to be the latest. They ae needed only for the d64 related command.

**Pull request closed without merging**
