### PR TITLE
Squeeze file and directory names if they are too long

### PR DESCRIPTION
**Pull request by naali**
Adds an UI option to "User Interface Settings" -> "Filename overflow squeeze"
that allows user to select the squeeze point (None/Beginning/Middle/End)

Kind of fixes "Long file name, can name be scrolled?":
https://github.com/GideonZ/1541ultimate/issues/212

### CODE REVIEW

**Comment by naali** [comment]
Options for setting the squeeze point:
squeeze-options


How long filenames look when squeeze point is set to middle:
filenames

This is how squeezed directory names look like when squeeze point is set to beginning:
directories

**Comment by Grrrolf** [comment]
Thank you for making this configurable 👍

**Comment by Mclaneinc** [comment]
Bit late to ask but will there be a shortcut key press to allow it on the fly which just cycles through the 3 styles of the squeezing

**Comment by GideonZ** [comment]
Shortcut keys are a common request for many different features. Which means
that they need to be factored out into a common, preferably programmable,
mechanism.
So at this point: no.

**Comment by Mclaneinc** [comment]
No problem, just glad to be getting the new feature..Thank you..

**Pull request merged**
